"""initial schema

Revision ID: ef171a701513
Revises: 
Create Date: 2026-04-24 23:41:39.364869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef171a701513'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=True),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_escalation', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('send_time', sa.String(length=5), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("send_time GLOB '[0-2][0-9]:[0-5][0-9]'", name='ck_users_send_time_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('chores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('frequency_days > 0', name='ck_chores_frequency_positive'),
    sa.CheckConstraint('priority IN (0, 1)', name='ck_chores_priority_valid'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.create_index('ix_chores_enabled', ['enabled'], unique=False)

    op.create_table('invite_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('intended_name', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('magic_link_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('magic_link_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_magic_link_expires', ['expires_at'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_from_user_id', sa.Integer(), nullable=True),
    sa.Column('rolled_over_from_assignment_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','completed','skipped','ignored','overdue','escalated')", name='ck_assignments_status_valid'),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['escalated_from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rolled_over_from_assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index('ix_assignments_chore_date', ['chore_id', 'assigned_date'], unique=False)
        batch_op.create_index('ix_assignments_status', ['status'], unique=False)
        batch_op.create_index('ix_assignments_user_date', ['user_id', 'assigned_date'], unique=False)

    op.create_table('chore_eligibility',
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.CheckConstraint("mode IN ('allow', 'deny')", name='ck_eligibility_mode_valid'),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chore_id', 'user_id')
    )
    op.create_table('reminder_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('daily_send','hourly_reminder','escalation','admin_notify')", name='ck_reminders_kind_valid'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder_events', schema=None) as batch_op:
        batch_op.create_index('ix_reminders_assignment', ['assignment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_events', schema=None) as batch_op:
        batch_op.drop_index('ix_reminders_assignment')

    op.drop_table('reminder_events')
    op.drop_table('chore_eligibility')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_assignments_user_date')
        batch_op.drop_index('ix_assignments_status')
        batch_op.drop_index('ix_assignments_chore_date')

    op.drop_table('assignments')
    with op.batch_alter_table('magic_link_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_magic_link_expires')

    op.drop_table('magic_link_tokens')
    op.drop_table('invite_codes')
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_index('ix_chores_enabled')

    op.drop_table('chores')
    op.drop_table('users')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
